package players.bots.utils;

import game.GamePanel;
import game.GameSetup;
import game.events.GameEvent;
import gamerules.*;
import gamerules.evaluation_functions.NeuralNetworkEval;
import gamerules.evaluation_functions.NormalizedSGD;
import players.Player;
import players.bots.AlphaBeta;
import players.bots.GreedyMST;
import players.bots.NaivePlayer;
import players.bots.RandomGreedy;

import java.awt.Color;
import java.io.IOException;
import java.util.LinkedList;
import java.util.List;
import java.util.Random;
import java.util.function.Supplier;

import static players.bots.utils.EveryoneShouldHaveMachineLearning.*;
import static players.bots.utils.NeuralNetwork.*;

public class DeepLearning {
    private static NeuralNetwork ann = null;
    private static Board game;
    private static int index = 0;
    private static double [] input;
    private static final double [] expected = new double[1];
    private static final NormalizedSGD heuristic = new NormalizedSGD();
    private static boolean loaded = false;

    private static boolean smart_learn = false;
    public static int max_turns_per_game = 2000;
    public static int iterations = -1; // don't limit
    public static double learning_rate = 0.0003;
    /** should be lower than save_time and stop_time */
    public static long info_time_ms = 1000;//300000l; // 5 minutes
    public static long save_time_ms = 900000l / 3l; // 15 minutes
    public static long stop_time_ms = 21600000l / 3; // 6 hours
    public static BoardRep board_rep = BoardRep.TwoNoNegatives;
    
    private static String network_name = "DL-smallTNN";

    public static void main(String[] args) throws IOException {
    	try {
    		ann = loadNetwork(network_name);
    		loaded = true;
    	} catch (NetworkIOException e) {
    		System.out.println("could not load network "+network_name);
    		e.printStackTrace();
    	}
    	if (!loaded) {
	        int[] structure = {162, 40, 1};
	        // The different activation function use in the ANN
	        NeuralNetwork.Activation[] activations = {SILU, SIGMOID};
	        ann = new NeuralNetwork(structure, activations);
	        ann.initializeRandomWeights(-1, 1);
	        System.out.println("Generated new ANN weights");
        } else {
        	System.out.println("loaded ANN from memory");
        }
    	NeuralNetwork old = ann.clone();
        associatedWithEuristic();
        saveNetwork(ann, network_name);
        GameEvent.clearAll(); // this removes all the events generated by the test games
        Player newANN = new NaivePlayer(new NeuralNetworkEval(ann));
        newANN.setName("new ANN"); newANN.setColor(Color.green);
        Player oldANN = new NaivePlayer(new NeuralNetworkEval(old));
        oldANN.setName("old ANN"); oldANN.setColor(Color.red);
        runGame(oldANN, newANN);
        runGame(newANN, oldANN);
    }

    public static void associatedWithEuristic(){
        Supplier<double[][]> problem = () -> {
            test();
            return new double[][] {input, expected};
        };
        System.out.println("Training through gradient descent...");
        GradientDescent GD = new GradientDescent(ann, HALF_SQUARE_ERROR, learning_rate, iterations);
        long time = System.currentTimeMillis();
        long start_time = time;
        GD.start(problem);
        try {
            Thread.sleep(10);
        } catch (InterruptedException e1) {}
        while (GD.isBusy()) {
        	if (System.currentTimeMillis() - time >= save_time_ms) {
        		saveNetwork(ann, network_name);
        		ann = loadNetwork(network_name);
        		time = System.currentTimeMillis();
        		System.gc();
        		System.out.println("Saved Network to version "+getLatestVersion(network_name));
        	}
        	if (System.currentTimeMillis() - start_time >= stop_time_ms) {
        		saveNetwork(ann, network_name);
        		GD.stop();
        		System.out.println("Stopped gradient descent after "+((System.currentTimeMillis() - start_time)/1000d)+" seconds");
        	}
            try {
                Thread.sleep(info_time_ms);
            } catch (InterruptedException e) {}
            if (GD.hasNewData()) {
            	System.out.format("calculated %d iterations\n", GD.getIterations());
            	System.out.format("  Loss = % .3e (+/- %.3e)\n",GD.getCurrentLoss(), GD.getCurrentLossSD());
            }
        }
    }

    private static void test(){
    	if (smart_learn) {
    		smartLearn();
    		return;
    	}
        if (game != null && game.noWinners()){
            GameState gs = new GameState(game);
            input = gs.getMatrixUnrolled(game.currentPlayer(), board_rep);
            expected[0] = heuristic.apply(gs,game.currentPlayer());
            game.forceRequestMoveAndContinue();
            if(index++ <= max_turns_per_game) return;
        }
        game = getRandomGameSetup();
        index = 0;
        test();
    }
    
    private static Player[] randomgameplayers = { new AlphaBeta(), new RandomGreedy(new NormalizedSGD(), 5.5), new GreedyMST() };
    private static Color[] playerColors = {Color.red, Color.green, Color.blue, Color.magenta, Color.cyan, Color.yellow};
    
    /** Generates a random game setup:<br>
     * 50% chance for 1v1<br>
     * 25% chance for 2v2<br>
     * 25% chance for 3v3<br>
     * for any player:<br>
     *  ~25% chance for RG(ANN)<br>
     *  ~25% chance for RG(SGD)<br>
     *  ~25% chance for random-MCTS<br>
     *  ~25% chance for AlphaBeta (but 0% chance for AlphaBeta v AlphaBeta on 1v1, 2v2 or 3v3; since AB is deterministic)
     */
    private static Board getRandomGameSetup() {
    	Random random = new Random();
    	GameSetup gs = new GameSetup();
    	Player[] players;
    	if (random.nextBoolean())
    		players = pick_random_players(2);
    	else if (random.nextBoolean())
    		players = pick_random_players(4);
    	else
    		players = pick_random_players(6);
    	for (int i=0; i < players.length; i++)
    		gs.addPlayer(players[i], "testplayer"+(i+1), playerColors[i]);
    	return gs.getBoard();
    }
    
    private static Random random;
    
    private static Player[] pick_random_players(int amount) {
    	if (random == null) random = new Random();
    	Player[] result = new Player[amount];
    	int[] temp = new int[amount];
    	while (filledWith(temp, 0))
    		for (int i=0; i < temp.length; i++) temp[i] = random.nextInt(4);
    	for (int i=0; i < temp.length; i++)
    		if (temp[i] == 3) result[i] = new RandomGreedy(new NeuralNetworkEval(ann, board_rep), 5.5);
    		else result[i] = randomgameplayers[temp[i]];
    	return result;
    }
    private static boolean filledWith(int[] a, int x) {
    	for (int i=0; i < a.length; i++)
    		if (a[i] != x) return false;
    	return true;
    }

    private static List<Double> state_outputs = new LinkedList<>();
    private static List<double[]> state_inputs = new LinkedList<>();
    private static boolean player_order = true;

    private static void smartLearn() {
		if (state_outputs.isEmpty()) {
			Player player1 = new AlphaBeta();
			player1.setName("player1");
			Player player2 = new GreedyMST();
			player2.setName("player2");
			GameState gs;
			List<double[]> state1_inputs = new LinkedList<>();
			List<double[]> state2_inputs = new LinkedList<>();
			int iter = 0;
			int max_iter = max_turns_per_game;
			if (player_order) game = new Board(GameRules.SELECTED_GAMERULES, null, player1, player2);
			else game = new Board(GameRules.SELECTED_GAMERULES, null, player2, player1);
			while (game.noWinners() && iter++ <= max_iter) {
				gs = new GameState(game);
	            if (game.currentPlayer() == player1) state1_inputs.add(gs.getMatrixUnrolled(player1, board_rep));
	            if (game.currentPlayer() == player2) state2_inputs.add(gs.getMatrixUnrolled(player2, board_rep));
	            game.forceRequestMoveAndContinue();
			} gs = new GameState(game);
			//System.out.println("winner = "+game.getWinner());
			double output;
			if (iter >= max_iter) {
				output = heuristic.eval(gs, player1);
				double norm = heuristic.eval(gs, player2) + output;
				output /= norm;
			} else output = (game.getWinner() == player1)? 1:0;
			//System.out.println("game output = "+output);
			for (int i=0; i < state1_inputs.size(); i++) {
				state_outputs.add(output);
				state_inputs.add(state1_inputs.get(i));
			}
			for (int i=0; i < state2_inputs.size(); i++) {
				state_outputs.add(1 - output);
				state_inputs.add(state2_inputs.get(i));
			}
			System.out.println("Game output set to "+output);

			player_order = !player_order;
		}
		int random = (int) (Math.random() * state_inputs.size());
		input = state_inputs.remove(random);
		expected[0] = state_outputs.remove(random);
    }

    private static void runGame(Player...players) {
    	GameSetup gs = new GameSetup();
		for (int i=0; i < 6 && i < players.length; i++) {
			gs.addPlayer(players[i], players[i].getName(), players[i].getColor());
		}
		GamePanel.startGame(gs);
    }
}
