package players.bots.utils;

import game.GamePanel;
import game.GameSetup;
import game.events.GameEvent;
import gamerules.*;
import gamerules.evaluation_functions.MCNormalized;
import gamerules.evaluation_functions.NeuralNetworkEval;
import gamerules.evaluation_functions.NormalizedSGD;
import gamerules.evaluation_functions.SimpleGoalDistance;
import players.Player;
import players.bots.*;

import java.awt.Color;
import java.io.IOException;
import java.util.LinkedList;
import java.util.List;
import java.util.Random;
import java.util.function.Supplier;

import static players.bots.utils.EveryoneShouldHaveMachineLearning.*;
import static players.bots.utils.NeuralNetwork.*;

public class DeepLearning {
    private static NeuralNetwork ann = null;
    private static Board game;
    private static int index = 0;
    private static double [] input;
    private static final double [] expected = new double[1];
    private static final EvaluationFunction heuristic = new MCNormalized(new MCNormalized(new NeuralNetworkEval(loadNetwork("DL-working test"))));
    private static boolean loaded = false;

    private static boolean smart_learn = false;
    public static int max_turns_per_game = 2000;
    public static int iterations = -1; // don't limit
    public static double learning_rate = 0.4;
    /** should be lower than save_time and stop_time */
    public static long info_time_ms = 300000l / 3; // 5 minutes
    public static long save_time_ms = 900000l / 3; // 15 minutes
    public static long stop_time_ms = 21600000l / 6; // 6 hours
    public static BoardRep board_rep = BoardRep.TwoNoNegatives;
    
    private static String network_name = "DL-working test";
    
    public static void main(String[] args) throws IOException {
    	try {
    		ann = loadNetwork(network_name);
    		loaded = true;
    	} catch (NetworkIOException e) {
    		System.out.println("could not load network "+network_name);
    		e.printStackTrace();
    	}
    	if (!loaded) {
	        int[] structure = {162, 40, 1};
	        // The different activation function use in the ANN
	        NeuralNetwork.Activation[] activations = {dSILU, SIGMOID};
	        ann = new NeuralNetwork(structure, activations);
	        ann.initializeRandomWeights(-1, 1);
	        System.out.println("Generated new ANN weights");
        } else {
        	System.out.println("loaded ANN from memory");
        }
    	//NeuralNetwork old = ann.clone();
        associatedWithEuristic();/*
        if (save_on_stop && !stopped_by_time) saveNetwork(ann, network_name);
        GameEvent.clearAll(); // this removes all the events generated by the test games
        Player newANN = new NaivePlayer(new NeuralNetworkEval(ann));
        newANN.setName("new ANN"); newANN.setColor(Color.green);
        Player oldANN = new NaivePlayer(new NeuralNetworkEval(old));
        oldANN.setName("old ANN"); oldANN.setColor(Color.red);
        runGame(oldANN, newANN);
        runGame(newANN, oldANN);
        */
    }

    public static void associatedWithEuristic(){
        Supplier<double[][]> problem = () -> {
            test();
            return new double[][] {input, expected};
        };
        System.out.println("Training through gradient descent...");
        GradientDescent GD = new GradientDescent(ann, HALF_SQUARE_ERROR, learning_rate, iterations);
//        GD.setDynamicLR(true, 1.25, 25);
//        GD.setExploration(true, 0.5, 25, null);
//        GD.setMinMaxLR(0.05, 0.5);
        runDeepLearning(GD, List.of(problem), stop_time_ms, save_time_ms, info_time_ms, network_name);
    }
    
    public static class DLThread extends Thread {
    	public boolean silence = false;
		public boolean stop = false;
		public final GradientDescent GD;
		public final List<Supplier<double[][]>> problems;
		public final long stop_time_ms, save_time_ms, info_time_ms;
		public final String network_name;
		public DLThread (GradientDescent GD, List<Supplier<double[][]>>problems, long stop_time_ms, long save_time_ms, long info_time_ms, String network_name) {
			this.GD = GD; this.problems = problems;
			this.stop_time_ms = stop_time_ms;
			this.save_time_ms = save_time_ms;
			this.info_time_ms = info_time_ms;
			this.network_name = network_name;
		}
		public DLThread (GradientDescent GD, Supplier<double[][]>problem, long stop_time_ms, long save_time_ms, long info_time_ms, String network_name) {
			this(GD, List.of(problem), stop_time_ms, save_time_ms, info_time_ms, network_name);
		}
		public void stopDL() {
			stop = true;
		}
		public void setSilent(boolean silent) {
			silence = silent;
		}
		@Override
		public void run() {
			System.out.format("set times to: (%.2f s; %.2f min; %.2f min)\n",info_time_ms/1000d, save_time_ms/1000d/60d, stop_time_ms/1000d/60d);
			long time = System.currentTimeMillis();
	        long start_time = time;
	        for (Supplier<double[][]> problem : problems) {
	        	if (stop) break;
		        GD.start(problem);
		        try {
		        	Thread.sleep(15);
				} catch (InterruptedException e1) {
					e1.printStackTrace();
				}
		        while (GD.isBusy()) {
		        	if (System.currentTimeMillis() - time >= save_time_ms) {
		        		saveNetwork((NeuralNetwork)GD.getModel(), network_name);
		        		time = System.currentTimeMillis();
		        		System.gc();
		        		if (!silence) System.out.println("Saved Network \""+network_name+"\" to version "+getLatestVersion(network_name));
		        	}
		        	if (System.currentTimeMillis() - start_time >= stop_time_ms) {
		        		saveNetwork((NeuralNetwork)GD.getModel(), network_name);
		        		GD.stop();
		        		stop = true;
		        		System.out.println("Stopped gradient descent on \""+network_name+"\" after "+((System.currentTimeMillis() - start_time)/1000d)+" seconds");
		        	}
		            try {
		                Thread.sleep(info_time_ms);
		            } catch (InterruptedException e) {}
		            if (GD.hasNewData())
		            	if (!silence) System.out.format("calculated %d iterations for \"%s\"\n"
		            			+ "  Loss = % .3e (+/- %.3e)\n"
		            			+ "  executed %d replacements\n"
		            			+ "  learning-rate = %.3f\n",
		            			GD.getIterations(), network_name, GD.getCurrentLoss(), GD.getCurrentLossSD(),
		            			GD.getExplorationReplacements(), GD.getLearningRate());
		        }
	        }
		}
	}
    
    public static DLThread runDeepLearning(GradientDescent GD, List<Supplier<double[][]>> problems, long stop_time_ms, long save_time_ms, long info_time_ms, String network_name) {
    	DLThread dl = new DLThread(GD, problems, stop_time_ms, save_time_ms, info_time_ms, network_name);
    	dl.start();
    	return dl;
    }
    public static DLThread runDeepLearning(GradientDescent GD, Supplier<double[][]> problem, long stop_time_ms, long save_time_ms, long info_time_ms, String network_name) {
    	return runDeepLearning(GD, List.of(problem), stop_time_ms, save_time_ms, info_time_ms, network_name);
    }

    private static void test(){
    	if (smart_learn) {
    		smartLearn();
    		return;
    	}
        if (game != null && game.noWinners()){
            GameState gs = new GameState(game);
			game.forceRequestMoveAndContinue();
            input = gs.getMatrixUnrolled(game.currentPlayer(), board_rep);
            expected[0] = heuristic.apply(new GameState(gs, game.lastMove),game.currentPlayer());
            if(index++ <= max_turns_per_game) return;
        }
        game = getRandomGameSetup();
        index = 0;
        test();
    }
    
    private static Player[] randomgameplayers = { new RandomGreedy(new NormalizedSGD(), 7), new RandomGreedy(new NormalizedSGD(), 6),  new RandomGreedy(new NormalizedSGD(), 5) };
    private static Color[] playerColors = {Color.red, Color.green, Color.blue, Color.magenta, Color.cyan, Color.yellow};
    
    /** Generates a random game setup:<br>
     * 50% chance for 1v1<br>
     * 25% chance for 2v2<br>
     * 25% chance for 3v3<br>
     * for any player:<br>
     *  ~25% chance for RG(ANN)<br>
     *  ~25% chance for RG(SGD)<br>
     *  ~25% chance for random-MCTS<br>
     *  ~25% chance for AlphaBeta (but 0% chance for AlphaBeta v AlphaBeta on 1v1, 2v2 or 3v3; since AB is deterministic)
     */
    private static Board getRandomGameSetup() {
    	Random random = new Random();
    	GameSetup gs = new GameSetup();
    	Player[] players;
//    	if (Math.random() < .25)
    		players = pick_random_players(2);
//    	else if (Math.random() < .25)
//    		players = pick_random_players(4);
//    	else if (Math.random() < .25)
//    		players = pick_random_players(6);
//    	else
//    		players = pick_random_players(1);
    	for (int i=0; i < players.length; i++)
    		gs.addPlayer(players[i], "testplayer"+(i+1), playerColors[i]);
    	return gs.getBoard();
    }
    
    private static Random random;
    
    private static Player[] pick_random_players(int amount) {
    	if (random == null) random = new Random();
    	Player[] result = new Player[amount];
    	int[] temp = new int[amount];
    	while (filledWith(temp, 0))
    		for (int i=0; i < temp.length; i++) temp[i] = random.nextInt(4);
    	for (int i=0; i < temp.length; i++)
    		if (temp[i] == 3) result[i] = new RandomGreedy(new NeuralNetworkEval(ann, board_rep), 5.5);
    		else result[i] = randomgameplayers[temp[i]];//new NaivePlayerGreedy();
    	return result;
    }
    private static boolean filledWith(int[] a, int x) {
    	for (int i=0; i < a.length; i++)
    		if (a[i] != x) return false;
    	return true;
    }

    private static List<Double> state_outputs = new LinkedList<>();
    private static List<double[]> state_inputs = new LinkedList<>();
    private static boolean player_order = true;

    private static void smartLearn() {
		if (state_outputs.isEmpty()) {
			Player[] players = pick_random_players(2);
			Player player1 = players[0]; //new AlphaBeta();
			player1.setName("player1");
			Player player2 = players[1]; //new GreedyMST();
			player2.setName("player2");
			GameState gs;
			List<double[]> state1_inputs = new LinkedList<>();
			List<double[]> state2_inputs = new LinkedList<>();
			int iter = 0;
			int max_iter = max_turns_per_game;
			if (new Random().nextBoolean())game = new Board(GameRules.SELECTED_GAMERULES, null, player1, player2);
			else game = new Board(GameRules.SELECTED_GAMERULES, null, player2, player1);
			while (game.noWinners() && iter++ <= max_iter) {
				gs = new GameState(game);
	            if (game.currentPlayer() == player1) state1_inputs.add(gs.getMatrixUnrolled(player1, board_rep));
	            if (game.currentPlayer() == player2) state2_inputs.add(gs.getMatrixUnrolled(player2, board_rep));
	            game.forceRequestMoveAndContinue();
			} gs = new GameState(game);
			//System.out.println("winner = "+game.getWinner());
			double output;
			if (iter >= max_iter) {
				output = heuristic.eval(gs, player1);
				double norm = heuristic.eval(gs, player2) + output;
				output /= norm;
			} else output = (game.getWinner() == player1)? 1:0;
			//System.out.println("game output = "+output);
			for (int i=0; i < state1_inputs.size(); i++) {
				state_outputs.add(output);
				state_inputs.add(state1_inputs.get(i));
			}
			for (int i=0; i < state2_inputs.size(); i++) {
				state_outputs.add(1 - output);
				state_inputs.add(state2_inputs.get(i));
			}
			//System.out.println("Game output set to "+output);

			player_order = !player_order;
		}
		int random = (int) (Math.random() * state_inputs.size());
		input = state_inputs.remove(random);
		expected[0] = state_outputs.remove(random);
    }

    private static void runGame(Player...players) {
    	GameSetup gs = new GameSetup();
		for (int i=0; i < 6 && i < players.length; i++) {
			gs.addPlayer(players[i], players[i].getName(), players[i].getColor());
		}
		GamePanel.startGame(gs);
    }
}
